version: "3.9"

services:
  backend:
    build: .
    container_name: animalngo-backend
    ports:
      - "5001:5001"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: animalngo
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: animalngo-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: animalngo
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
