apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: animal-ngo-backend-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5001
  selector:
    app: animal-ngo-backend
  type: LoadBalancer
status:
  loadBalancer: {}
